### PR TITLE
JSON stringify the graphql result

### PR DESCRIPTION
**Pull request by nerdkid93**
This change fixed my issue related to https://github.com/enonic/lib-guillotine/issues/65

### CODE REVIEW

**Comment by sigdestad** [comment]
Question to this and changes in lib guillotine? Are we jdon stringifying two times? Also, what was done in app guillotine?

**Comment by alansemenov** [comment]
No changes in any other repos except for this PR which adds `JSON.stringify` of query response received from `lib-graphql`.

**Comment by sigdestad** [comment]
Ok, but I have seen pull req and similar in lib guillotine also?

**Comment by alansemenov** [comment]
No, we decided not to do that to avoid breaking changes.

**Comment by sigdestad** [comment]
Sweet.. Also, graphQL is used back-end, so I think things may be different there?

**Comment by alansemenov** [comment]
Yes, since `JSON.stringify` fixes the display of null values it means that response from the GraphQL lib actually contains them.

**Pull request merged**
